# Generated by Django 5.2.8 on 2025-11-13 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField(help_text='O período completo a ser analisado.', verbose_name='Texto do Período')),
                ('tipo_periodo', models.CharField(choices=[('SIMPLES', 'Simples'), ('COMPOSTO', 'Composto')], default='SIMPLES', max_length=10, verbose_name='Tipo de Período')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='Oracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_oracao', models.TextField(help_text='O trecho da oração dentro do período.', verbose_name='Texto da Oração')),
                ('tipo_oracao', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('COORDENADA', 'Coordenada'), ('SUBORDINADA_SUBSTANTIVA', 'Subordinada Substantiva'), ('SUBORDINADA_ADJETIVA', 'Subordinada Adjetiva'), ('SUBORDINADA_ADVERBIAL', 'Subordinada Adverbial'), ('REDUZIDA', 'Reduzida')], default='PRINCIPAL', max_length=50, verbose_name='Tipo de Oração')),
                ('oracao_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinadas', to='catalogacao.oracao', verbose_name='Oração Principal/Regente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oracoes', to='catalogacao.periodo', verbose_name='Período de Origem')),
            ],
            options={
                'verbose_name': 'Oração',
                'verbose_name_plural': 'Orações',
            },
        ),
        migrations.CreateModel(
            name='ComponenteSintatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_componente', models.CharField(choices=[('SUJEITO', 'Sujeito'), ('PREDICADO', 'Predicado')], max_length=10, verbose_name='Tipo de Componente')),
                ('texto_componente', models.TextField(help_text='O trecho que corresponde ao sujeito ou predicado.', verbose_name='Texto do Componente')),
                ('classificacao', models.CharField(blank=True, help_text='Ex: Simples, Composto, Oculto, Indeterminado (para Sujeito); Verbal, Nominal, Verbo-Nominal (para Predicado).', max_length=50, null=True, verbose_name='Classificação Detalhada')),
                ('oracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='catalogacao.oracao', verbose_name='Oração')),
            ],
            options={
                'verbose_name': 'Componente Sintático',
                'verbose_name_plural': 'Componentes Sintáticos',
                'unique_together': {('oracao', 'tipo_componente')},
            },
        ),
    ]
